### ISSUE TITLE
Missing Key field in Address

### ISSUE THREAD

**Issue by zackpollard** [commercetools/commercetools-dotnet-sdk#100]
.NET `Address` does not reflect the spec.

https://docs.commercetools.com/http-api-types.html#address

The `key` field is missing in the Class specification

**Comment by jenschude** [comment]
The field has been added and released with https://www.nuget.org/packages/commercetools.NET.SDK/1.1.0.629-dev

**Comment by zackpollard** [comment]
Excellent, thanks for the quick response! :)
