### ISSUE TITLE
Missing isMatching field in ShippingRate

### ISSUE THREAD

**Issue by alemhnan** [commercetools/commercetools-dotnet-sdk#103]
.NET ShippingRate does not reflect the spec.

https://docs.commercetools.com/http-api-projects-shippingMethods#shippingrate

The key isMatching is missing in the Class specifications

**Comment by alemhnan** [comment]
@jenschude have you had the chance to take a look at this? 

I've tried to open a PR but I can't get to make the tests run locally, I'm not sure which are the correct credentials for the API (I've tried to give full access but I still get auth errors)

**Comment by alemhnan** [comment]
Thanks a lot! @jenschude

**Comment by jenschude** [comment]
Pushed to nuget as 1.1.0.636-dev
