### ISSUE TITLE
No 'Key' field on Customer or CustomerDraft

### ISSUE THREAD

**Issue by Max-John** [commercetools/commercetools-dotnet-sdk#105]
.NET Customer and CustomerDraft does not reflect the spec.

https://docs.commercetools.com/http-api-projects-customers#customerdraft
https://docs.commercetools.com/http-api-projects-customers#customer

The key field is missing in the Class specification for each

**Comment by jenschude** [comment]
The key field has been added and released on NuGet as version 1.1.0.642-dev
