### ISSUE TITLE
Optional parameters in UpdateActions

### ISSUE THREAD

**Issue by jayS-de** [commercetools/commercetools-dotnet-sdk#11]
The RemoveLineItemAction has an optional parameter quantity. The implementation uses a default value of 0. But this value should not be transported on the API when not set else the line item will not be removed.

I didn't checked for other update actions and optional parameters but most likely this can happen also at other update action models

**Comment by jhumber** [comment]
The quantity parameter has been removed from the RemoveLineItemAction constructor.  I am working on removing the others.
