### ISSUE TITLE
Custom fields on categories?

### ISSUE THREAD

**Issue by andersekdahl** [commercetools/commercetools-dotnet-sdk#116]
Hi!
We're forced to use this SDK instead of the .NET Core one in one integration where .NET Core isn't supported. And I just noticed that https://github.com/commercetools/commercetools-dotnet-sdk/blob/master/commercetools.NET/Categories/Category.cs is missing a `Custom` property for custom fields. Will this be fixed?

Thanks!

**Comment by jenschude** [comment]
Btw the Core SDK targets only netstandard 2.0 which means that it should be possible using it with .NET Framework >= 4.6.1. I just created a small example to the Core SDK.

https://github.com/commercetools/commercetools-dotnet-core-sdk/pull/137

**Comment by andersekdahl** [comment]
Ah, just assumed that it was Core only, I'll try using that! Thanks!
