### ISSUE TITLE
MessageQueryResult includes empty Results

### ISSUE THREAD

**Issue by houbena** [commercetools/commercetools-dotnet-sdk#18]
The response to QueryMessagesAsync seems to include the count of the messages but not the messages themselves.

Although response.Result.Count is 20 (as the screenshot shows), Results is empty in the same response.

<img width="995" alt="screen shot 2017-05-23 at 10 13 19 am" src="https://cloud.githubusercontent.com/assets/8375842/26344691/ce781bb6-3fa0-11e7-9c21-9aaacd7dd284.png">

**Comment by nkuehn** [comment]
@houbena  you should assign or contact someone from Falcon here - they do not get automatic notifications because this repo is in our organization.  E.g. @jhumber

**Comment by jhumber** [comment]
@nkuehn I do get automatic notifications.

@houbena Thanks for reporting this. I'll be having a look at this issue today.

**Comment by jhumber** [comment]
@houbena Today's commit to the master branch resolves this issue.
