### ISSUE TITLE
Decide on Git Branching and Release Model 

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-dotnet-sdk#3]
Concerning branching two options:
- Gitflow (like PHP SDK):  "develop" is the trunk-like branch where feature branches are merged into.  "master" represents the last stable release.  versions are tags on the master branch. 
- Plain Git: (like JVM SDK)  "master" ist the trunk-like branch

Concerning release Model:
- I suggest semantic versioning like we do with PHP and JVM SDKs (http://semver.org/ ).  If ok, please document in the README 
- concerning pre-1.0 release naming : probably depends on the package manager's assumptions.  Please propose something.  In PHP and JVM we did  "1.0.0-M1" counting milestone releases.  But something was not good about it, but I don't know what any more. 

@jayS-de  @schleichardt @lauraluiz  @jhumber  Please decide somehow.  It just needs to be defined.

**Comment by schleichardt** [comment]
Yes, don't use the milestone names, this is not semantic versioning and not expressing if new versions were bug fixes or feature versions. Also thousands of milestone sound worse than sth like 0.13.2.

**Comment by jhumber** [comment]
Branching: I'd prefer plain Git if that suits everyone else.

Versioning: Semantic versioning sounds good, and I agree with @lauraluiz regarding the numbering.

Are we considering what is up now a pre-1.0 release?  We currently have the .NET assembly at v1.0.1.0 as we've committed the first version and a patch already.  I can update the .NET assembly info if everyone feels we should be pre-1.0 right now.

**Comment by nkuehn** [comment]
@jhumber  here's your questions as a copy:

> The main question is, what version should our current build be?  In your initial comment in the issue, you made reference to the current build being pre-1.0 so I am wondering what a good number to start with would be, if not 1.0.0.0.
>  
> There are additional considerations regarding versioning in a .NET project, especially since we will be publishing this project on NuGet.  The built assembly file of a .NET project has a version number that consists of four parts, using the format N.N.N.N, and the parts are typically used in this way: {Major Version}.{Minor Version}.{Build Number}.{Revision}.  The version number for the current build is stored in a file in the .NET solution, which you can see here:
>  
> https://github.com/commercetools/commercetools-dotnet-sdk/blob/master/commercetools.NET/Properties/AssemblyInfo.cs
>  
> The idea would be that if we go ahead with the plain Git model, every time we commit changes to the master branch, the version would also change in the AssemblyInfo.cs file.  This same version number would be reflected in the published NuGet package so everything stays consistent. 
>  
> There is also the question about how to handle pre-release or release candidate versions of the SDK.  We can only use numeric values in the .NET assembly version, but we wouldn't be publishing release candidates through NuGet, so it may be that we just have the pre-release or release candidate versioning in GitHub, if that makes sense.

Thanks for pointing out that the dotnet implementation has a defined versioning logic (which is actually a good thing).  

To not over-engineer it we did only publish pre-release versions before the first stable API 1.0.0  in our JVM and PHP SDKs and since then "just did it".  

I found a proposal from microsoft on the semantics that matches my impression of the names: https://msdn.microsoft.com/en-us/library/ms973869.aspx#managevers_topic2   
"build" is a concept I don't see a need for in this case - suggesting to just make it a zero all the time.  
So semantic versioning `1.5.2` could be dotnet `1.5.0.2`.   

It's only about publishing since CI should build and test every commit anyways - so no "build" numbers required anyways. 

Short form:

We could start with `0.0.0.1` as prerelease, basically just counting up the last number als milestones, then decide it's good and re-tag the last prerelease as `1.0.0.0`. 

And to stay "dotnetty" and easy to understand I suggest to also work with  the dotnet `1.5.0.2` form in Git Tags, documentation etc. and just define the semantics in the README:
 * semver major = dotnet major  -> incompatible
 * semver minor = dotnet minor  -> compatible, API surface increased
 *  dotnet build = zero (unused in this project) 
 * semver patch = dotnet revision -> compatible, just internal changes

**Comment by jayS-de** [comment]
As i created now a build script which uses as base the one from nunit, we should also stick to their versioning scheme.

- Tags are semantic version numbers using: {major}.{minor}.{patch}
- Master is versioned as: {major}.{minor}.{patch}-dev-{build}
- Branches use {major}.{minor}.{patch}-ci-{build}-{branch-name}

All changes to master or tags are pushed automatically to NuGet.

And I started using 1.0.0 as initial version number

**Comment by nkuehn** [comment]
@jayS-de  can you document the pattern in the README as "How to release"?
