### ISSUE TITLE
Do a one-time feature completeness check on Carts and Discount features

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-dotnet-sdk#32]
A relevant customer project is starting on this SDK that will use the Discount and Cart related APIs heavily.  

To not bring extra risk into their project timeline we would like to do a one-time feature coverage check on the data fields, update actions and API calls.   -> i.e. check the "breadth" of the coverage. 

Reference is the API documentation: 

https://dev.commercetools.com/http-api-projects-carts.html
https://dev.commercetools.com/http-api-projects-cartDiscounts.html
https://dev.commercetools.com/http-api-projects-discountCodes.html

TODO: product discounts, too? 

The "depth" of coverage will remain as-is since it's currently not planned to e.g. add fully typed query buildersn or similar features to the .NET SDK.

**Comment by brajivbala** [comment]
@nkuehn  at the moment we don't plan to use product discounts. But things can change quickly. So It would be relevant to check product discount also.

**Comment by jhumber** [comment]
@nkuehn Sure, I can take care of this review today.

**Comment by jhumber** [comment]
@nkuehn Carts has been checked and the following issues were resolved:

* commercetools.Carts.Cart class was missing the refusedGifts property.
* commercetools.Carts.CustomLineItemDraft class was missing the externalTaxRate property.
* commercetools.Carts.DiscountedLineItemPriceForQuantity class properties were incorrect.
* commercetools.Carts.LineItemDraft class was missing the externalPrice and externalTotalPrice properties.
* commercetools.Carts.LineItemMode enum was not yet implemented.
* commercetools.Carts.LineItemPriceMode enum was missing the ExternalPrice property.
* commercetools.Carts.UpdateActions.AddShoppingListAction was not yet implemented.
* commercetools.Carts.UpdateActions.SetDeleteDaysAfterLastModificationAction was not yet implemented.
* commercetools.Carts.UpdateActions.SetLineItemAction was not yet implemented.

These changes have not yet been merged into the master branch. I will be looking at Cart Discounts next.
