### ISSUE TITLE
Set up automatic testing on Travis (+Travis account)

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-dotnet-sdk#4]
Since the repository is public we can use the free travis like with the other SDKs

https://docs.travis-ci.com/user/getting-started/
https://docs.travis-ci.com/user/languages/csharp/

It should be configured to automatically build pull requests. 

A status badge on the README is appreciated.

**Comment by nkuehn** [comment]
@commercetools/ops could someone with admin rights on this repo be so nice to activate it on travis-ci.org?  Thank you! 

https://travis-ci.org/profile/commercetools

**Comment by svenmueller** [comment]
@nkuehn done. the project is now connected with travis-ci.org

**Comment by nkuehn** [comment]
@svenmueller  Thank you!  

@jhumber  you can take over now to create an initial working .travis.yml file.  It's normal that you need to commit and push changes to it to get it running via a bit of trial and error since you don't have the travis environment locally.

**Comment by nkuehn** [comment]
PS: I was too curious and tried it out in e2c28a2b46d6ded1f3550ac6ddba8ba6db9cb8ba

**Comment by nkuehn** [comment]
@jhumber  I did all I could do with my exisiting travis knowledge, need to go home, too.  The open topics are all .NET -specific so I cannot help a lot. 

But maybe this can help you:  an "official" travis CI config example from microsoft:  https://github.com/dotnet/docs/blob/master/.travis.yml   (I don't know why they're running the software on CI instead of testing it, but that does not really matter now)

I did not continue because I can't even get the `dotnet build` command running (it wants project.json files)

So maybe we start with documenting the correct build and test CLI calls to the README first.

**Comment by jhumber** [comment]
@nkuehn The failed job is expected as the project only targets the .NET 4.5.1 framework right now. This is reflected in the README under the Supported Platforms heading.  

I will get the project building locally against .NET Core and add the needed files to the repo.  I expect to have this done by the end of the week.

**Comment by nkuehn** [comment]
thanks, the versioning is really confusing.  I just learnt that all mono 4.* versions implement the dotnet 4.5 profile (also mono 4.2, 4.6 etc.), so the versions are totally unrelated.  And I learnt that dotnet core 1.0* is rather a dotnet 5.* in terms of API compatibility.  
What a mess, and I thought the Javascript language versions are confusing.  

But nevertheless: If you look into the log the failure is just because it doesn't even start to build (you do need an explicit build script in travis for the dotnet core runtime).

**Comment by jhumber** [comment]
The new target for adding the .NET Core solution files to the repo is sometime next week. I've run into a few issues and I am still looking into the best way to resolve them.

**Comment by jayS-de** [comment]
Added a appveyor config with #9

**Comment by jayS-de** [comment]
AppVeyor CI: https://ci.appveyor.com/project/commercetools/commercetools-dotnet-sdk
Travis CI: https://travis-ci.org/commercetools/commercetools-dotnet-sdk

**Comment by nkuehn** [comment]
👍   very nice!
