### ISSUE TITLE
Decide where to do general documentation, tutorials etc. 

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-dotnet-sdk#5]
Since @jhumber  and his Falcon colleagues don't get access to editing our https://dev.commercetools.com site where the tutorials and general pages on the JVM SDK live we could consider writing the HOWTOs and other version-agnostic content somewhere else. 

Options:
- markdown files in the repository (in the root dir or a "doc" folder). 
- github wiki feature ( https://github.com/commercetools/commercetools-dotnet-sdk/wiki )
-  the CT developer website ( via a person at commercetools that does the changes on request)
- more ideas? 

@jhumber @stmeissner please vote or propose something.  

I prefer the github wiki as it's most approachable.  known downside: embedding images is a bit of a hassle.

**Comment by jhumber** [comment]
I think the GitHub Wiki feature is suitable for the documentation.

**Comment by stmeissner** [comment]
I also vote for the GitHub Wiki for two reasons

- it's
 close to the source code
- can
 be maintained by the developers without me being in the loop

**Comment by nkuehn** [comment]
OK, decision made. I'll set up an initial page and a link from the readme.
