### ISSUE TITLE
Add Images to Products is not working

### ISSUE THREAD

**Issue by jenschude** [commercetools/commercetools-dotnet-sdk#52]
```csharp
ProductDraft newDraft = new ProductDraft(productName, resourceIdentifier, productSlug);
….
                JObject itemFieldValue = new JObject
                            {
                                { "url", "http://someurl.jpg"},
                                {"dimensions", new JObject{{"w", 1500},{"h", 1500} } },
                                {"label", "some label"}
                            };
               Image image = new Image(itemFieldValue);
                List<Image> images = new List<Image>() { image };
                newDraft.MasterVariant.Images = images;
….
                                  Response<Product> productResponse = await client.Products().CreateProductAsync(productDraft);
```

The reason for this can be identified as the properties for the image are deserialized in a flat manner. But there is no special handler for serializing the Image back to the expected JSON structure of the API. So it's not possible to create products with images as well to set them using the update actions.

**Comment by jenschude** [comment]
@purquhart could you or someone else fix this please

**Comment by purquhart** [comment]
Updated in #49 

Fixed "Adding images to product draft not working"
- Included update to ShouldCreateAndDeleteProductAsync test, to confirm success of adding images
- Added HashCode helper struct

**Comment by purquhart** [comment]
Hmm it looks like the branch it was committed to has been deleted. Please let me know if you want me to create a new branch, commit, and re-pull @jenschude
