### ISSUE TITLE
CustomerGroup support

### ISSUE THREAD

**Issue by damarna85** [commercetools/commercetools-dotnet-sdk#56]
Hi,

We are trying to get a customer group by key but we do not find the proper method to do that. Is this included in the SDK?

Thanks!

**Comment by JoostBollen** [comment]
@sshibani any chance of getting this implemented? Otherwise we can just build this on an implementation of IClient when it's released.

**Comment by sshibani** [comment]
@JoostBollen Yes, please use the IClient and implement the missing method for now.
