### ISSUE TITLE
HttpClient is created and disposed on every request

### ISSUE THREAD

**Issue by bjornsallarp** [commercetools/commercetools-dotnet-sdk#57]
Creating and disposing HttpClient on every request is not recomended. See:
[Improper Instantiation antipattern](https://docs.microsoft.com/en-us/azure/architecture/antipatterns/improper-instantiation/)
[You're Using HttpClient Wrong and it is Destabilizing Your Software](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/)

I suggest that Client instead take a HttpClient constructor argument and use that instance. Lifetime of the HttpClient is managed by the consuming application and thus also making it possible to orchestrate HttpClients with whichever delegate handlers needed. The logging delegate handler currently enforced could be removed (also dropping log4net dependency). Perhaps put that handler in the examples project for reference.

**Comment by JoostBollen** [comment]
This is also causing issues with me. Dropping log4net would be great as we're running API apps. Would be nice if we can find a way to use Application Insights TelemetryClient.

**Comment by bjornsallarp** [comment]
I haven't used Application Insights to confirm/test this myself but I believe that with aspnet core HttpClient will automatically log to Application Insights without adding custom delegate handlers. Look at David Fowlers response in this issue for more details: https://github.com/aspnet/Hosting/issues/1164#issuecomment-322027443

Here's documentation about correlation ids that tie into Application Insights and HttpClient:
https://docs.microsoft.com/en-us/azure/application-insights/application-insights-correlation

Now, not everyone use aspnet core yet. By adding a constructor that take an instance of HttpClient to Client it is possible to construct that HttpClient with whatever delegate handlers. Ie, an application insights delegate handler could be inserted into the HttpClient pipline before handing it over to Commercetools Client.

I've been thinking of how to fix this issue without breaking existing functionality and it would require some refactoring of Client before allowing a new constructor for HttpClient. Would you accept such a pull request?

**Comment by jenschude** [comment]
Fixed with #60
