### ISSUE TITLE
HttpClient disposed

### ISSUE THREAD

**Issue by sshibani** [commercetools/commercetools-dotnet-sdk#58]
Is the `Using` statement here necessary?

https://github.com/commercetools/commercetools-dotnet-sdk/blob/master/commercetools.NET/Common/Client.cs#L87

The HttpClient should be a shared object and is thread-safe. for more information please read this blog post: 

https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

**Comment by JoostBollen** [comment]
Please keep in mind while solving this, that we need the ability to extend functionality to the Commercetool Client, which will require to have the HttpClient publicly available.

**Comment by bjornsallarp** [comment]
I filed the exact same issue hours ago #57 . Close this issue and continue discussions there?

**Comment by jenschude** [comment]
Fixed with #62
