### ISSUE TITLE
configure for and publish on nuGet

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-dotnet-sdk#7]
The SDKs have all been published as usable artifacts way before the final release to push adoption and feedback.   

nuGet seems to be the de facto standard package repository and is even natively integrated into Visuals Studio. 

Instructions here https://docs.nuget.org/ndocs/quickstart/create-and-publish-a-package  

In addition to the `.nuspec` file we'll need a nuGet account  ( https://www.nuget.org/users/account/LogOn  )

@stmeissner @hajoeichler who's usually holding and managing such accounts?  e.g. like mavencentral, PHP packagist etc. ?

**Comment by stmeissner** [comment]
@nkuehn Such accounts are usually hold and managed by our ops team with access granted to lead developers.

**Comment by nkuehn** [comment]
@commercetools/ops  could someone please register an official commercetools nuGet account so we can publish the dotnet SDK there? 
https://www.nuget.org/users/account/LogOn 

Thank you!

**Comment by svenmueller** [comment]
The account is created. Who needs access? Would be OK to just define two ENV vars in travis with username/password so that travis is able to access the nuget service?

- `NUGET_USERNAME`
- `NUGET_PASSWORD`

**Comment by svenmueller** [comment]
<img width="1042" alt="bildschirmfoto 2016-11-23 um 15 32 02" src="https://cloud.githubusercontent.com/assets/131689/20565483/05239566-b192-11e6-9d9f-0fa2bef6e622.png">

**Comment by svenmueller** [comment]
i also added an ENV `NUGET_API_KEY` containing the actual api key

**Comment by nkuehn** [comment]
@svenmueller  cool, thank you very much! 

@jhumber  we'll have to talk about how to get this up and running. You'll first have to set up the .nuspec file and we'll then have to solve the puzzle of how to publish or not publish pre-releases on nuGet. 

https://docs.nuget.org/ndocs/create-packages/prerelease-packages

**Comment by jayS-de** [comment]
Resolved by #15
