### ISSUE TITLE
ProductVariantAvailability properties are always NULL

### ISSUE THREAD

**Issue by enggaardt** [commercetools/commercetools-dotnet-sdk#86]
It looks like the ProductVariantAvailability object on a ProductVariant does not get initialized properly.

In the raw JSON data the availability data is an array of availability for each channel.

However the ProductVariantAvailability class is only a single object that is passed that a array in the constructor.

Which then fails to populate the 3 availability properties because the dynamic data object passed to it is an array.

**Comment by enggaardt** [comment]
...or rather the availability data is a dictionary with the channel IDs as the keys.

**Comment by jenschude** [comment]
I just merged the feature to deserialize the availability per channel:

https://github.com/commercetools/commercetools-dotnet-sdk/blob/170d86771d94f8443efd605dd1cebcd1424eab4b/commercetools.NET.Tests/ProductProjectionManagerTest.cs#L146
