### ISSUE TITLE
Multiple Scopes in Client Configuration

### ISSUE THREAD

**Issue by HenryKeen** [commercetools/commercetools-dotnet-sdk#95]
Hi

I'm not sure if I'm missing something but it looks like its only possible to specify a single scope in the `Configuration` object. I have a requirement to get products and manage orders in the same project and would prefer to not have to make multiple clients.

Is there something I'm missing?

Thanks,
Henry

**Comment by jenschude** [comment]
I just merged a fix for this issue. Please see https://github.com/commercetools/commercetools-dotnet-sdk/blob/master/commercetools.NET.Tests/ProjectScopeTest.cs for details how to define multiple scopes
